<a href="https://colab.research.google.com/github/BaranovTim/Pytorch_course/blob/main/tensor_course_YT_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as pit

print(torch.__version__)

2.5.1+cu121


In [ ]:
scalar = torch.tensor(7)
print(scalar)

#get as an int
scalar.item()

tensor(7)


7

In [ ]:
#vector
vector = torch.tensor([7, 7])
print(vector)

tensor([7, 7])


In [ ]:
#matrix
matrix = torch.tensor([[7, 8],
                      [9, 10 ]])
matrix

matrix.ndim

matrix[0]

matrix.shape

torch.Size([2, 2])

In [ ]:
#tensor
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

tensor.ndim

tensor.shape

tensor[0][1][1]

tensor(5)

In [ ]:
tensor_1 = torch.tensor([ [[1,2,3],[1,2,3],[1,2,3]],
                          [[0,9,8],[0,9,8],[0,9,8]],
                          [[5,6,7],[5,6,7],[5,6,7]]])
tensor_1.shape
tensor.ndim
tensor_1[0]

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [ ]:
# random tensors

#they are important because the way neural networks learn is that they start with tensors full
#of random numbers and then adjust(регулируют) those random numbers to better represent the data

# start with random numbers -> look at data -> update random numbers -> look at rand num -> update


#create a random tensor of size(shape) (3, 4)

random_tensor = torch.rand(3, 4)
print(random_tensor)

random_tensor.ndim

tensor([[0.5766, 0.9979, 0.4028, 0.5352],
        [0.4490, 0.9587, 0.2358, 0.6220],
        [0.5584, 0.9565, 0.6695, 0.4231]])


2

In [ ]:
# random tensor with similar size to an image tensor

random_img_size_tensor = torch.rand(size=(224,224,3)) # height, width, colour
random_img_size_tensor.shape, random_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
# tensor of zeros

zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#tensor of ones

ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
#a range of tensors and tensor-like

one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
range_with_steps = torch.arange(0,101, 5)
range_with_steps

tensor([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
         70,  75,  80,  85,  90,  95, 100])

In [ ]:
#creating tensors like - тензор на подобии уже существующего, где одинаков размер, но не данные

ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#tensor datatypes

#float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, #what datatype is the tensor eg(float32 or float16 etc)
                               device = None, #what device if your tensor on, like cpu or gpu or cuda
                               requires_grad= False) #whether or not to track gradients with these tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
float_what_type = float_16_tensor * float_32_tensor
float_what_type.dtype #float32

torch.float32

In [ ]:
tensor_01 = torch.tensor([1, 2, 3])
tensor_01 + 10
tensor_01 * 10
tensor_01 - 10
tensor_01 / 10

#same thing but using built in functions
torch.mul(tensor_01, 10)
torch.add(tensor_01, 10)
torch.sub(tensor_01, 10)
torch.div(tensor_01, 10)

#matrix multiplication
#means first tensor's rows * second tensor's columns
# so like [1,2,3],
#         [4,5,6]
#                 *
#                   [7,8],
#                   [9,10],
#                   [11,12] = 1*7 + 2*9 + 3*11 = 58
# and do it for each
# the ans: [58, 64],
#          [139, 154]

print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) * tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Equals: tensor([[[ 1,  4,  9],
         [16, 25, 36],
         [49, 64, 81]]])


In [ ]:
tensor_02 = torch.tensor([1,2,3])
torch.matmul(tensor_02, tensor_02)


tensor(14)

In [ ]:
tensor_02 @ tensor_02

tensor(14)

### Rules


1.   The inner dimensions must match:

*   (3, 2) @ (3, 2) won't work
*   (3, 2) @ (2, 3) will work
*   (2, 3) @ (3, 2) will work
        ^     ^
        |     |
    inner dimensions
    

2.   The resulting marix has the shape of the **outer dimensions**:
*   (2, 3) @ (3, 2) -> (2, 2)
*   (3, 2) @ (2, 3) -> (3, 3)



In [ ]:
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

torch.mm(tensor_A, tensor_B) # tensor.mm = tensor.matmul = @


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix out tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A transpose switches the axes or dimensions of a given tensor

In [ ]:
tensor_B2 = tensor_B.T
tensor_B2

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_A @ tensor_B2

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
# Finding min, max, mean, sum, etc

x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
x.max()

tensor(90)

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.sum()

tensor(450)

In [ ]:
max = x.max()
a=0
for i in x:
  if i == max:
    print(a)
  a += 1

9


In [ ]:
x.argmin() # index of a min number
x.argmax() # index of a max number

tensor(9)

In [ ]:
import torch
x= torch.arange(1., 11.)
x.shape, x

(torch.Size([10]), tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
#add an extra dimension
x_reshaped = x.reshape(1, 10)
x_reshaped

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
x_reshaped_2 = x.reshape(2, 5)
x_reshaped_2

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [ ]:
#change the view
z = x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
#view is the same as reshape, but if we change z, then x will also be changed
# a view of a tensor shares the same memory as the original tensor
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
#stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([4, 10]))

In [ ]:
x_squeezed = torch.squeeze(x)
x_squeezed

tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
x_unsqueezed = torch.unsqueeze(x_squeezed, dim=0)
x_unsqueezed

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
x_orig = torch.rand(224, 224, 3) # height, width, colour channel
x_permuted = x_orig.permute(2, 0, 1) # 0->1; 1->2; 2->0
x_permuted, x_permuted.shape

(tensor([[[0.8289, 0.5105, 0.9454,  ..., 0.7461, 0.0401, 0.8820],
          [0.7607, 0.1645, 0.6808,  ..., 0.0100, 0.5319, 0.8366],
          [0.2227, 0.7526, 0.3135,  ..., 0.2808, 0.4184, 0.2801],
          ...,
          [0.0995, 0.2445, 0.7068,  ..., 0.3997, 0.9916, 0.4727],
          [0.8694, 0.5074, 0.0445,  ..., 0.7041, 0.2844, 0.3210],
          [0.7728, 0.6853, 0.9105,  ..., 0.7127, 0.2787, 0.6416]],
 
         [[0.0816, 0.8373, 0.2359,  ..., 0.0613, 0.2925, 0.0438],
          [0.7254, 0.9698, 0.4405,  ..., 0.9416, 0.7456, 0.4099],
          [0.1499, 0.5395, 0.5685,  ..., 0.4174, 0.8419, 0.6475],
          ...,
          [0.9209, 0.0142, 0.2338,  ..., 0.6027, 0.6664, 0.3484],
          [0.6010, 0.7448, 0.9414,  ..., 0.0580, 0.8746, 0.2336],
          [0.4218, 0.6469, 0.5326,  ..., 0.5669, 0.2069, 0.1029]],
 
         [[0.9596, 0.9051, 0.3467,  ..., 0.7899, 0.5427, 0.0059],
          [0.3777, 0.2164, 0.1960,  ..., 0.6305, 0.5428, 0.7211],
          [0.5087, 0.7175, 0.3548,  ...,

In [ ]:
#Indexing
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0, 0, 0]

tensor(1)

In [ ]:
#Use ':' to select 'all'
x[:, :, 2]

tensor([[3, 6, 9]])

In [ ]:
#NumPy

import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor_orig = torch.ones(7)
tensor_numpy = tensor_orig.numpy()
tensor_numpy

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

To reduce the randomness in neural networks and Pytorch comes the concept of a random seed

Essentially what the random seed does is 'flavour' the randomness

In [ ]:
import torch

tensor_randA = torch.rand(3, 4)
tensor_randB = torch.rand(3, 4)

print(tensor_randA)
print(tensor_randB)
print(tensor_randA == tensor_randB)

tensor([[0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464],
        [0.7890, 0.2814, 0.7886, 0.5895]])
tensor([[0.7539, 0.1952, 0.0050, 0.3068],
        [0.1165, 0.9103, 0.6440, 0.7071],
        [0.6581, 0.4913, 0.8913, 0.1447]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
RANDOM_SEED = 42 # any number
torch.manual_seed(RANDOM_SEED)
tensor_randC = torch.rand(3, 4)

tensor_randD = torch.rand(3, 4)

print(tensor_randC)
print(tensor_randD)
print(tensor_randC == tensor_randD)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
RANDOM_SEED = 42 # any number
torch.manual_seed(RANDOM_SEED)
tensor_randC = torch.rand(3, 4)
#нужно прописывать к каждому тензору чтобы было одинакого
torch.manual_seed(RANDOM_SEED)
tensor_randD = torch.rand(3, 4)

print(tensor_randC)
print(tensor_randD)
print(tensor_randC == tensor_randD)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


#Running tensors and Pytorch objects on the GPUs (and making faster computations)

1. Getting a GPU

 - Using a google colab for a free GPU
 - Use ur own
 - Use cloud computing - GCP, AWS, Azure, these allow u to rent computers on the cloud and access them

 2. Check for GPU access with Pytorch

 - torch.cuda.is_available()
 - setup device agnostic code:
    device = 'cuda' if torch.cuda.is_available else 'cpu'


In [ ]:
import torch
torch.cuda.is_available()


True

In [ ]:
device = 'cuda' if torch.cuda.is_available else 'cpu'
device

torch.cuda.device_count()

1

#Putting tensors and models on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [ ]:
#create a tensor (default on CPU)

tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#Move tensor to GPU if available
device = 'cuda' if torch.cuda.is_available else 'cpu'
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
#if tensor is on GPU, can't transform it to Numpy
#tensor_on_gpu.numpy()
#error

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])